export const BOWLING_STYLE = [
  "Right Arm Fast",
  "Right Arm Fast Medium",
  "Right Arm Medium",
  "Right Arm Orthodox",
  "Right Arm Chinaman",
  "Right Arm Off Break",
  "Right Arm Leg Break",
  "Right Arm Slow",
  "Left Arm Fast",
  "Left Arm Fast Medium",
  "Left Arm Medium",
  "Left Arm Orthodox",
  "Left Arm Chinaman",
  "Left Arm Off Break",
  "Left Arm Leg Break",
  "Left Arm Slow",
  "None",
  "",
];
